---
# tasks file for sshpassDownloadProxy

- name: download file "{{ download_this_file }}"
  script: downloadSftp.sh "{{ v_usr }}" "{{ v_pass }}" "{{ v_server }}" "{{ v_remotePath }}" "{{ v_localPath }}" "{{ download_this_file }}" "{{ proxy }}" "{{ puerto }}"
  tags:
    - playme
